### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by ghost**
ON RHEL 7.6 and may be earlier. The current block does not work. I came across this in another project. The only way I found it does work is a shell script like the one provided.

### CODE REVIEW

**Comment by HarryHarcourt** [comment]
I think I noted something similar, but cannot remember the specifics. 
Instead of using the command, look at this URL, I will try it in the next couple of days

https://stackoverflow.com/questions/41053331/ansible-how-to-restart-auditd-service-on-centos-7-get-error-about-dependency

**Comment by ghost** [comment]
I just tested the code that I recommended for PR on RHEL 7.6. It ran with a warning, but worked.

**Comment by HarryHarcourt** [comment]
Hi Roman
Let me test it with the Ansible Devs recommended solution and get back to you.
I know the shell will work, but we do want to reduce the warnings.
Best
Ben

**Comment by ghost** [comment]
Can also do.
```
- name: Restart auditd
  shell: service auditd restart
  args:
    warn: no
```

Runs as:
```
RUNNING HANDLER [Ansible-RHEL7-CIS-Benchmarks : Restart auditd] ************************************
changed: [192.168.2.106]
```

**Comment by HarryHarcourt** [comment]
Hi Roman
I have updated the latest master to version 1.1.36, by updating the handlers/main.yml in the way the Ansible Developers indicated it should be done
- service: 
  name: auditd 
  state: restarted 
  use: service
I do understand that "shell" can be used, but I am trying to keep to the modules written, otherwise we could simply do everything via a "command" or a "shell". 
Please remember this is about "state".
I really thank you for raising the issue, please continue to contribute, this challenge you identified I had noted before but forgot to address.
Many thanks!
Best
Ben

**Pull request closed without merging**
